### ISSUE TITLE
Possible bug with input file location

### ISSUE THREAD

**Issue by michael-kotliar** [GuanLab/Leopard#2]
It looks like this [line](https://github.com/GuanLab/Leopard/blob/6278ecd3b56f1a8221ef43dbc4814766bdc1615a/code_1bp/predict.py#L35) has a bug. Perhaps, it should be something like this `path_computer='data/'`

```
Traceback (most recent call last):
  File "code_1bp/predict.py", line 76, in <module>
    dict_dna[the_id]=pyBigWig.open(path1 + the_id + '.bigwig')
RuntimeError: Received an error during file opening!
[urlOpen] Couldn't open ../data/dna_bigwig/A.bigwig for reading
[urlOpen] Couldn't open ../data/dna_bigwig/A.bigwig for reading
```

**Comment by Hongyang449** [comment]
You are right (I have subfolders when I developed this code). Now I have fixed the path bug in `predict.py` and it should be fine now. Thanks!

**Comment by michael-kotliar** [comment]
Cool! Thanks!
